### ISSUE TITLE
Suitable for News Messages?

### ISSUE THREAD

**Issue by pswerbung** [codefog/contao-social_images#11]
Hello, we have the problem, that News-Messages from Contao also need this (ever changing) og:image Meta-Description in layout_full-View.  Example:
http://evpzh.ch/aktuelles/lesen/rathaus-news-darum-ging-es-heute-u-a-im-kantonsrat-kopie-186.html

How can we get the actual News (Teaser) Image to show up as og:image-Meta-Tag?

**Comment by qzminski** [comment]
Is the news teaser image set and the "Add image" checkbox is checked? Then it should work as below method is responsible for handling that:

https://github.com/codefog/contao-social_images/blob/master/classes/SocialImages.php#L349

You can also contact me privately and we can debug it together on your system.
