### ISSUE TITLE
Tried to use your extension with Contao 4

### ISSUE THREAD

**Issue by netzarbeiter** [codefog/contao-social_images#14]
There is no field in the page layout settings to activate this extension.

![bildschirmfoto 2017-05-10 um 21 57 37](https://cloud.githubusercontent.com/assets/1942550/25918460/c74484f8-35cb-11e7-8ee0-7efcef5574ab.png)

I could enable it in the root page of the site structure and choose the image.

No output in the head-section of the front end.

**Comment by qzminski** [comment]
Fixed in d525b13.
