### ISSUE TITLE
Disable for individual pages

### ISSUE THREAD

**Issue by stefanschleich** [codefog/contao-social_images#17]
I think it would be useful to have the ability to disable the functionality for certain pages in the site structure.

In my case I created a landing page where I moved `$this->head;` in `fe_page.html5` from the `<head>` to the end of the `<body>` to prevent JS-files from blocking DOM rendering. This leads to having `<meta>` tags in the body. I know this is an edge case but maybe it could be useful in other scenarios too.

**Comment by fritzmg** [comment]
You would have to do that for _every_ extension, that puts something into the `<head>`. Instead you should simply move only the JavaScript out of there.

**Comment by qzminski** [comment]
If you want to disable the social images just create another page layout and turn it off there.

`$this->head` as its name says is made especially for the `<head>` section and if you would want to move JS to the bottom of the page you should use either some regexp or adjust the extensions accordingly.

**Comment by stefanschleich** [comment]
> This makes no sense, as you would have to do that for every extension that puts something into the <head>. Instead you should simply move only the JavaScript out of there.

You're right, but how would I get the files I defined as static in j_scripts.html5 to NOT get added to the header but to any other place instead?

> If you want to disable the social images just create another page layout and turn it off there.

I just did but it has no effect. The tags are written even with social images not activated in the layout.

**Comment by fritzmg** [comment]
> You're right, but how would I get the files I defined as static in j_scripts.html5 to NOT get added to the header but to any other place instead?

You can use extensions like Theme+ for that, may be also Supertheme. Or you do it with your own PHP script.

**Comment by stefanschleich** [comment]
> You can use extensions like Theme+ for that, may be also Supertheme. 

I'll have a look. Thanks!

**Comment by qzminski** [comment]
> I just did but it has no effect. The tags are written even with social images not activated in the layout.

Are you 100% sure it's not working? This line should prevent that https://github.com/codefog/contao-social_images/blob/master/classes/SocialImages.php#L103

Where do you add the social images in this case? Page settings, content elements, news, etc.?

**Comment by stefanschleich** [comment]
> Are you 100% sure it's not working?

I just updated from version 3.2. to 3.3. and now it works. Sorry for the trouble.
