### ISSUE TITLE
Generate og:image:width and og:image:height

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-social_images#19]
When a content is shared on Facebook for the first time, the share dialogue won't show the `og:image` right away. There are two ways to make Facebook show the share image even when the URL is shared for the first time: https://stackoverflow.com/a/30361572/374996

Within Contao it probably makes sense to take the second approach, i.e. generating `og:image:width` and `og:image:height`.

_Note:_ I realize your extension allows for more than one `og:image` to be present for legacy reasons. May be this feature should be dropped? I don't think there is any reason anymore to have more than one `og:image` defined.

**Comment by qzminski** [comment]
> Note: I realize your extension allows for more than one og:image to be present for legacy reasons. May be this feature should be dropped? I don't think there is any reason anymore to have more than one og:image defined.

I think it's mostly there to give the user a choice which image he would like to use. Would it harm if we add `og:image:width` and `og:image:height` to all images?

**Comment by fritzmg** [comment]
> I think it's mostly there to give the user a choice which image he would like to use.

Well, where can you do that? Facebook for instance does not offer to switch through multiple share images, when sharing a post.

> Would it harm if we add og:image:width and og:image:height to all images?

I suppose not - though it would generate a lot of additional markup. Also, how would you be able to identify which `og:image:width` belongs to which `og:image`?

**Comment by qzminski** [comment]
> Well, where can you do that? Facebook for instance does not offer to switch through multiple share images, when sharing a post.

This must have changed because at the time I developed this extension it was possible. Or was it another service... 🤔

> I suppose not - though it would generate a lot of additional markup. Also, how would you be able to identify which og:image:width belongs to which og:image?

Just like a regular array: http://ogp.me/#array

**Comment by fritzmg** [comment]
> This must have changed because at the time I developed this extension it was possible. Or was it another service... 🤔

Yeah, it was possible in the past. That's why I said "for legacy reasons" ;)

**Comment by qzminski** [comment]
I would preserve the multiple selection of images as the OpenGraph protocol is not a Facebook protocol and other services are potentially making use of those arrays. Agreed?

**Comment by fritzmg** [comment]
Agreed.

**Comment by qzminski** [comment]
Implemented in d177f82 but this can produce unexpected results because of https://github.com/contao/core-bundle/issues/1214.

**Comment by fritzmg** [comment]
Yeah, see the comments though: you should just combine each `og:image`/`og:image:width`/`og:image:height` combo into one string.

**Comment by qzminski** [comment]
The 3223cd7 should do then.

**Comment by madmaharaja** [comment]
> 
> 
> > This must have changed because at the time I developed this extension it was possible. Or was it another service... 🤔
> 
> Yeah, it was possible in the past. That's why I said "for legacy reasons" ;)

Just bumped into this thread because I was looking for a way to add og:image:width and og:image:height to my page templates in Contao. Anyway, just for the record: It is still (or again?) possible to switch through and select from multiple ogimage files when sharing a URL on Facebook.

**Comment by fritzmg** [comment]
Yeah, I also noticed that this feature has returned on Facebook.
