### ISSUE TITLE
maximum image size setting

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-social_images#20]
If you allow pretty large images in your Contao installation and an editor happens to use a large image (eg. 5568x3712), Facebook for example might not use the image:

> Provided og:image URL, https://example.org/files/content/foo.jpg could not be downloaded because it exceeded the maximum allowed sized of 8Mb.

To counter act such instances it would make sense to provide an image size setting or simply a maximum size setting (in addition to the minimum size setting) in the page layout, so that the image can be downscaled automatically.

**Comment by qzminski** [comment]
Would you downscale the image or just ignore it (like for minimum size setting)?

Also, the Facebook error you get refers explicitly to the file size and not the image dimensions... although they are related they should not be considered the same.

**Comment by fritzmg** [comment]
> Would you downscale the image or just ignore it (like for minimum size setting)?

I would downscale it. This way one can also choose that each share image has the same format for example (cut or even zoomed to the important part).

**Comment by qzminski** [comment]
Erm... but that downscaling & cropping would happen only if the image has too big dimensions? Or would you then apply it to all images? 🤔

**Comment by fritzmg** [comment]
In Contao 4 images will not be upscaled, so it would only apply to images that have bigger dimensions by default.

In Contao 3 images would be upscaled.

**Comment by qzminski** [comment]
Can you check if 0b3591b fulfill your needs?

**Comment by fritzmg** [comment]
Yes 👍 :)

**Comment by qzminski** [comment]
Perfect, just released 3.5.0.
