### ISSUE TITLE
image URL is double encoded

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-social_images#23]
If the path to the social image is
```
files/content/FALTER_Scheckübergabe 2018 (c) Karin Wasner.jpeg
```
for example, the resulting `og:image` URL will be
```
https://example.org/files/content/FALTER_Scheck%25C3%25BCbergabe%25202018%2520%2528c%2529%2520Karin%2520Wasner.jpeg
```
i.e. the URL is double encoded. The correct URL would be
```
https://example.org/files/content/FALTER_Scheck%C3%BCbergabe%202018%20%28c%29%20Karin%20Wasner.jpeg
```
Tested in Contao 4.4.13 with Social Images 3.5.2.

**Comment by qzminski** [comment]
Hm I have set up the filename as you suggested but it seems to work fine for me:

```html
<meta property="og:image" content="http://tmp:8888/files/test/FALTER_Scheck%C3%BCbergabe%202018%20%28c%29%20Karin%20Wasner.jpg">
```

Can you find out which module includes this image (core, news, etc.) ?

**Comment by qzminski** [comment]
I am still unable to reproduce that on MacOS 🙈  can you find out the fix for yourself?

Is the image size calculated correctly? If it's double encoded then it should not work either...

**Comment by fritzmg** [comment]
Yeah, I'll debug :)

**Comment by fritzmg** [comment]
Ah, you need to set an image size in the page layout for the social images. `\Image::get` already encodes the image path. That's why it gets double encoded (even when it's not actually resized of course).

**Comment by fritzmg** [comment]
I'd propose the following:
```diff
    // Resize the image
    if ($resize[0] || $resize[1] || $resize[2]) {
-       $strImage = \Image::get($strImage, $resize[0], $resize[1], $resize[2]);
+       $strImage = urldecode(\Image::get($strImage, $resize[0], $resize[1], $resize[2]));
-       list($width, $height) = getimagesize(TL_ROOT . '/' . urldecode($strImage));
+       list($width, $height) = getimagesize(TL_ROOT . '/' . $strImage);
    }
```

**Comment by qzminski** [comment]
I was about to write exactly the same. Thanks, I will fix this soon!

**Comment by qzminski** [comment]
3.5.3 is released now.
