### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by madmaharaja** [codefog/contao-social_images#26]
I have been wanting to try this extension for quite a while -- thanks for the good work!

Anyway, I just installed it and it works fine. However, here are a few thoughts about how IMHO this extension could be significantly enhanced:

- Why only make it possible to add a social image to the root page? Why not give the option of adding individual images to potentially every page? So, that if you selected an image for a subpage it would overwrite the og:image that was selected for the root page. Otherwise, if no social image has been selected for a subpage, it could just "inherit" the next social image further up in the page tree. Because, as nice as it is to have semi-individual og:images by activating the current feature in the page layouts, it often is not ideal because the images one uses to be displayed in the frontend aren't necessarily optimized for the dimensions that Facebook etc. requires to generate a preview. Currently it's alway a bit of a lottery if an image will still look good the way Facebook crops it (approx. 16:8,4) but if you give the option of adding individual social images to every subpage one could optimize the og:images ...
- As far as I can tell, if you activate social images in a page layout, this extension checks for any embeded images in the sequence of how the different modules etc. are placed in the page layout. So first in the #header section and last in the #footer section. My problem: In the contao page layout, the right column (#right) always is placed before the main column. Even if I re-sort the frontend modules manually in a page layout -- as soon as I hit save, it sorts the right column modules above the main column:
![image](https://user-images.githubusercontent.com/3133710/63095072-92181080-bf6a-11e9-95aa-36e16b5871ad.png)
However, in my case, I only use the right column for secondary information and therefore the images that are placed there aren't at all useful for og:image (and it just happens to be that I have a video in the header instead of an image).
So, what I would like to suggest, would be to be able to determine or even to limit which layout sections should be used for social images -- and/or that one can determine in which order the extension should check for images in the layout (e.g. 1. #header, 2. #main, ✖ #right, ✖ #footer)
- It's great that one can determine minimum width/height for images. But I think it would be even better if one could limit the image ratio as well. Basically it would be enough to have a checkbox with the option "Don't use images in the portrait format (height > width)". Because (at least for Facebook) you will usually want to have preview images in the landscape format.

**Comment by fritzmg** [comment]
>     * Why only make it possible to add a social image to the root page? Why not give the option of adding individual images to potentially every page?

You can already do that.



>     * As far as I can tell, if you activate social images in a page layout, this extension checks for any embeded images in the sequence of how the different modules etc. are placed in the page layout. So first in the #header section and last in the #footer section

Not quite. On the news reader page for example, the news image will always come first.

**Comment by madmaharaja** [comment]
>>Why only make it possible to add a social image to the root page? Why not give the option of adding individual images to potentially every page?

>You can already do that.

Oh, great! Sorry, I had somehow not realized that.


>>As far as I can tell, if you activate social images in a page layout, this extension checks for any embeded images in the sequence of how the different modules etc. are placed in the page layout. So first in the #header section and last in the #footer section

>Not quite. On the news reader page for example, the news image will always come first.

Well, ok -- but that still doesn't solve the problem with all other pages when the og:images are "chosen" by the extension as defined in the page layout.

**Comment by fritzmg** [comment]
@qzminski may be you should be able to limit the automatic social images from content elements to a specific column? Like `main` for example.

**Comment by qzminski** [comment]
@fritzmg at some point this could be introduced, yes. However right now I am out of capacities for open source projects. I am open for sponsored features though if anyone would like to sponsor it.

**Comment by madmaharaja** [comment]
Mega -- danke!
