### ISSUE TITLE
Extension creates correct og:image but facebook takes another image (only on index)

### ISSUE THREAD

**Issue by netgroupgmbh** [codefog/contao-social_images#29]
Hi there!

I installed the extension in Contao 4.4.55 (https://www.weiterbildungsinstitut.de), enabled social media images in the page layout (number of images: 1) and chose one image (for all pages) in the website root (https://www.weiterbildungsinstitut.de/files/wbi/bilder/social-media/wbi_lehrgaenge.jpg 1000 x 667px).

The extension now creates the right code on every page of the site:
```
<meta property="og:image" content="https://www.weiterbildungsinstitut.de/files/wbi/bilder/social-media/wbi_lehrgaenge.jpg">
<meta property="og:image:width" content="1000">
<meta property="og:image:height" content="667">
```

Facebook: if I want to post a link of one of the following pages the correct image is suggested. And if I post "https://www.weiterbildungsinstitut.de/index.html" it also works ...

Only if I want to post "https://www.weiterbildungsinstitut.de" - **without "index.html"** - another image is suggested (https://www.weiterbildungsinstitut.de/files/wbi/bilder/standorte/dortmund/standort_dortmund.jpg). WHY?

I more like the look of an index URL without "index.html" ...
Do you habe any tips or suggestions?

Thanks and best wishes ... Tanja

**Comment by fritzmg** [comment]
If the correct og:image is in the HTML source for a given URL, then the extension works correctly. The extension itself obviously has no influence on what Facebook actually uses.

In order to debug such things you need to use Facebook's [Share Debugger](https://developers.facebook.com/tools/debug/). There you can also invalidate the image cache that Facebook uses for a given URL.

**Comment by qzminski** [comment]
@netgroupgmbh please follow the @fritzmg suggestion, I think it's related to the Facebook cache.

**Comment by netgroupgmbh** [comment]
Yes, regarding the HTML source code everything is fine ...
And indeed: it was the facebook cache! Using Facebook's Share Debugger helped a lot!

Thank you so much!
