### ISSUE TITLE
Could twitter:image support be added?

### ISSUE THREAD

**Issue by bright-cloud-studio** [codefog/contao-social_images#36]
Hi there,

We have used this package on a website and ran into an interesting situation. Although things worked as expected for Facebook, Twitter would not grab the correct image. After looking into it our best guess was that although there is an image linked in the og:image tag there was no twitter:image tag. 

Although I am not a fan of this, I modified [https://github.com/codefog/contao-social_images/blob/master/src/ImageGenerator.php](https://github.com/codefog/contao-social_images/blob/master/src/ImageGenerator.php) and copied line 91 and just changed og:image to twitter:image and now the twitter card is displaying the correct image.

Is it possible to add support for this natively? Either a checkbox to choose to use OpenGraph, Twitter cards or both? Just brainstorming.

**Comment by fritzmg** [comment]
Twitter falls back to `og:image` or the new meta tag as far as I know, so that's not really necessary imho.

**Comment by bright-cloud-studio** [comment]
Hmm, I wonder if maybe Twitter cached the card and that is why we were not seeing the changes reflecting with og:image. I wasn't aware that it used it as a fallback.
