### ISSUE TITLE
Cached images

### ISSUE THREAD

**Issue by cgpro** [codefog/contao-social_images#7]
Hi,

very nice extension. But Google+ displays the temporary images from contao. Every time I empty the cache, the images on the wall are disappearing.

Is it possible to change the og:image source to the original in the file store and not to the cached one in assets/images?

Rolf

**Comment by qzminski** [comment]
Can you paste your og:image tags here? Their path should never point to the temporary images that are located in /assets/images. Also, what version of the extension are you using?

**Comment by cgpro** [comment]
Hi Kamil,

sorry my fault! I've implemented the og:image functionality with an other extension and I thought its your social_images extension... *awkward*

Please close the ticket, but I've found something different: The manual of social_images is not working
http://codefog.pl/en/extension/social-images.html I get a page not found.

**Comment by qzminski** [comment]
The manual will be launched this week.
