### ISSUE TITLE
Small optimization in collectNewsImages

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-social_images#9]
Since the news modules already provide the actual path to the image file via the `singleSRC` variable of the template, a small optimization can be done in `collectNewsImages` :). This code:
```php
$objFile = \FilesModel::findByPk($arrData['singleSRC']);

if ($objFile !== null && is_file(TL_ROOT . '/' . $objFile->path))
{
    $GLOBALS['SOCIAL_IMAGES'][] = $objFile->path;
}
```
could be replaced by
```php
if (is_file(TL_ROOT . '/' . $objTemplate->singleSRC))
{
    $GLOBALS['SOCIAL_IMAGES'][] = $objTemplate->singleSRC;
}
```
and thus saves a database query.

**Comment by qzminski** [comment]
Two questions:
1. Are you sure the query is executed? The model should be already there in the model registry.
2. Are you sure that ```$objTemplate->singleSRC``` contains the path to full image and not to the thumbnail?

**Comment by fritzmg** [comment]
> 1. Are you sure the query is executed? The model should be already there in the model registry.

I haven't checked, but you are right of course, the result could already be in the model registry.

> 2. Are you sure that $objTemplate->singleSRC contains the path to full image and not to the thumbnail?

Yes, `$objTemplate->singleSRC` always contains the path to the full image (i.e. the image selected in your news entry), while `$objTemplate->src` contains the path to the thumbnail (or in Contao 3.4.x and onwards it is stored within `$objTemplate->picture` iirc).

**Comment by qzminski** [comment]
I think we can assume the model is already registered because of this line:

https://github.com/contao/core/blob/master/system/modules/news/modules/ModuleNews.php#L149
